[project]
name = "tarefas"
version = "0.1.0"
description = ""
authors = [
    {name = "Nicolezxfshd",email = "nicolezimmer@gmail.com"}
]
requires-python = ">=3.11,<4.0"
dependencies = [
    "sqlalchemy (>=2.0.48,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "fastapi (>=0.135.2,<0.136.0)",
    "uvicorn (>=0.42.0,<0.43.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "redis (>=5.0.0,<6.0.0)",
    "celery (>=5.6.3,<6.0.0)",
    "websockets (>=16.0,<17.0)",
    "kafka-python (>=3.0.2,<4.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest-mock (>=3.15.1,<4.0.0)"
]
